name: Ask Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type de version (patch, minor, major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump version and create git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version ${{ github.event.inputs.version_type }} -m "chore(release): %s"
          git push origin HEAD
          git push origin --tags